# Generated by Django 5.1 on 2024-08-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("web", models.URLField(blank=True, null=True)),
                ("email_address", models.EmailField(max_length=100)),
            ],
        ),
    ]
