# Generated by Django 5.1 on 2024-08-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyClubUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firs_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, verbose_name="User Email")),
            ],
        ),
        migrations.AlterField(
            model_name="venue",
            name="email_address",
            field=models.EmailField(max_length=100, verbose_name="Email Address"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Venue Name"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Contact Phone"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="web",
            field=models.URLField(
                blank=True, null=True, verbose_name="Website Address"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="zip_code",
            field=models.CharField(max_length=100, verbose_name="Zip Code"),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Event Name")),
                ("evint_date", models.DateTimeField(verbose_name="Event Date")),
                ("manager", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formsapp.venue",
                    ),
                ),
                (
                    "attendees",
                    models.ManyToManyField(blank=True, to="formsapp.myclubuser"),
                ),
            ],
        ),
    ]
