# Generated by Django 5.1 on 2024-08-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formsapp", "0002_myclubuser_alter_venue_email_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="evint_date",
            new_name="event_date",
        ),
    ]
