# Generated by Django 5.1 on 2024-08-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formsapp", "0003_rename_evint_date_event_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="email_address",
            field=models.EmailField(
                blank=True, max_length=100, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Contact Phone"
            ),
        ),
    ]
