# Generated by Django 5.1 on 2024-08-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formsapp", "0005_alter_event_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="owner",
            field=models.ImageField(
                default=1, upload_to="", verbose_name="Venue Owner"
            ),
        ),
    ]
