# Generated by Django 5.1 on 2024-08-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formsapp", "0006_venue_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="owner",
            field=models.IntegerField(default=1, verbose_name="Venue Owner"),
        ),
    ]
