# Generated by Django 5.1 on 2024-08-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formsapp", "0008_venue_venue_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venue",
            old_name="Venue_image",
            new_name="venue_image",
        ),
    ]
