# Generated by Django 5.1 on 2024-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formsapp", "0009_rename_venue_image_venue_venue_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
